title: "KLEP"
description: "Revolutionizing symbolic AI"
theme: jekyll-theme-cayman
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Docs"
    url: /docs
  - title: "Twitter"
    url: https://twitter.com/roll4d4
  - title: "Roll4d4.com"
    url: https://roll4d4.com
