title: "KLEP - Key Lock Executable Process"
description: "Revolutionizing symbolic AI"
theme: jekyll-theme-cayman 
url: "https://roll4d4.github.io/KLEP"
twitter_username: roll4d4
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Docs"
    url: /docs
  - title: "Twitter"
    url: https://twitter.com/roll4d4
  - title: "Roll4d4.com"
    url: https://roll4d4.com
